-- ===========================================================================
--  우리집 가계부 — Supabase 테이블 + 보안(RLS) 설정 스크립트
--  Supabase 대시보드 → SQL Editor 에 전체를 붙여넣고 Run 하세요.
--  여러 번 실행해도 안전합니다 (IF NOT EXISTS / DROP POLICY IF EXISTS).
--
--  ⚠️ 컬럼명은 반드시 camelCase 여야 합니다.
--     앱이 보내는 JSON 키가 categoryId / isFixed / createdAt 형태이므로
--     snake_case 로 만들면 조용히 실패합니다. 그래서 큰따옴표로 감쌌습니다.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. 테이블
-- ---------------------------------------------------------------------------

create table if not exists public.transactions (
  id              text primary key,
  date            date not null,
  type            text not null check (type in ('income', 'expense', 'transfer')),
  amount          bigint not null default 0,
  "userId"        text,
  "categoryId"    text,
  "sharedType"    text,
  "paymentMethod" text,
  "isFixed"       boolean default false,
  memo            text,
  "createdAt"     timestamptz default now(),
  "updatedAt"     timestamptz default now()
);

create index if not exists transactions_date_idx on public.transactions (date desc);

create table if not exists public.user_settings (
  id     text primary key,
  name   text,
  role   text,
  avatar text
);

create table if not exists public.categories (
  id    text primary key,
  type  text not null,
  name  text not null,
  icon  text,
  color text
);

create table if not exists public.budgets (
  id           text primary key,
  month        text not null,
  "categoryId" text not null,
  amount       bigint not null default 0
);

create index if not exists budgets_month_idx on public.budgets (month);

create table if not exists public.goals (
  id              text primary key,
  name            text not null,
  "targetAmount"  bigint not null default 0,
  "currentAmount" bigint not null default 0,
  "targetDate"    text,
  icon            text,
  color           text
);

create table if not exists public.accounts (
  id               text primary key,
  name             text not null,
  type             text not null default 'bank',
  owner            text default 'shared',
  "bankName"       text,
  "openingBalance" bigint not null default 0
);

create table if not exists public.recurring (
  id              text primary key,
  name            text not null,
  type            text not null default 'expense',
  amount          bigint not null default 0,
  "categoryId"    text,
  "userId"        text,
  "sharedType"    text,
  "paymentMethod" text,
  "accountId"     text,
  "dayOfMonth"    integer not null default 1,
  memo            text,
  active          boolean not null default true,
  "startMonth"    text,
  "endMonth"      text
);

create table if not exists public.settlements (
  id            text primary key,
  month         text not null,
  mode          text,
  amount        bigint not null default 0,
  "fromUserId"  text,
  "toUserId"    text,
  "sharedTotal" bigint not null default 0,
  "husbandPaid" bigint not null default 0,
  "wifePaid"    bigint not null default 0,
  "settledAt"   timestamptz default now()
);

create unique index if not exists settlements_month_idx on public.settlements (month);

-- 부부 공유 설정 (정산 기준 등). 항목이 늘어나도 스키마를 바꾸지 않도록 jsonb 로 둡니다.
create table if not exists public.app_settings (
  id   text primary key,
  data jsonb not null default '{}'::jsonb
);

-- 카드 청구 주기 컬럼 (기존 accounts 테이블에도 안전하게 추가됩니다)
alter table public.accounts add column if not exists "statementDay"       integer default 31;
alter table public.accounts add column if not exists "paymentDay"         integer default 25;
alter table public.accounts add column if not exists "paymentMonthOffset" integer default 1;
alter table public.accounts add column if not exists "paymentAccountId"   text;
alter table public.accounts add column if not exists "autoSettle"         boolean default false;

-- 반복 거래 금액 유형 (fixed = 자동 생성 / variable = 확인 후 입력)
alter table public.recurring add column if not exists "amountMode" text default 'fixed';
alter table public.recurring add column if not exists skips        text[] default '{}';

-- 거래 테이블에 계좌 / 반복거래 연결 컬럼 추가 (기존 테이블에도 안전하게 적용됩니다)
alter table public.transactions add column if not exists "accountId"     text;
alter table public.transactions add column if not exists "fromAccountId" text;
alter table public.transactions add column if not exists "toAccountId"   text;
alter table public.transactions add column if not exists "recurringId"   text;
alter table public.transactions add column if not exists "autoGenerated" boolean default false;
alter table public.transactions add column if not exists "cardBillingMonth" text;

-- 할부 (하나의 구매가 회차 수만큼의 거래로 나뉘어 저장됩니다)
alter table public.transactions add column if not exists "installmentId"        text;
alter table public.transactions add column if not exists "installmentSeq"       integer;
alter table public.transactions add column if not exists "installmentMonths"    integer;
alter table public.transactions add column if not exists "installmentPrincipal" bigint;
alter table public.transactions add column if not exists "installmentFee"       bigint default 0;
alter table public.transactions add column if not exists "installmentRate"      numeric default 0;

create index if not exists transactions_installment_idx on public.transactions ("installmentId");

-- ---------------------------------------------------------------------------
-- 2. 보안 (RLS) — 이 단계가 가장 중요합니다
--
--    anon key 는 브라우저 소스에 그대로 노출됩니다. RLS 가 꺼져 있으면
--    그 키를 본 누구나 가계부 전체를 읽고 지울 수 있습니다.
--    아래 정책은 "로그인한 사용자만" 접근을 허용합니다.
-- ---------------------------------------------------------------------------

alter table public.transactions  enable row level security;
alter table public.user_settings enable row level security;
alter table public.categories    enable row level security;
alter table public.budgets       enable row level security;
alter table public.goals         enable row level security;
alter table public.accounts      enable row level security;
alter table public.recurring     enable row level security;
alter table public.settlements   enable row level security;
alter table public.app_settings  enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array['transactions','user_settings','categories','budgets','goals','accounts','recurring','settlements','app_settings']
  loop
    execute format('drop policy if exists "authenticated_all" on public.%I', t);
    execute format($f$
      create policy "authenticated_all" on public.%I
        for all
        to authenticated
        using (true)
        with check (true)
    $f$, t);
  end loop;
end $$;

-- (선택) 부부 두 분의 이메일만 허용하고 싶다면 위 정책 대신 아래를 사용하세요.
-- 이메일 두 개를 실제 값으로 바꾼 뒤 실행하면 됩니다.
--
-- do $$
-- declare t text;
-- begin
--   foreach t in array array['transactions','user_settings','categories','budgets','goals','accounts','recurring','settlements','app_settings']
--   loop
--     execute format('drop policy if exists "authenticated_all" on public.%I', t);
--     execute format('drop policy if exists "household_only" on public.%I', t);
--     execute format($f$
--       create policy "household_only" on public.%I
--         for all to authenticated
--         using (auth.jwt() ->> 'email' in ('남편이메일@example.com','아내이메일@example.com'))
--         with check (auth.jwt() ->> 'email' in ('남편이메일@example.com','아내이메일@example.com'))
--     $f$, t);
--   end loop;
-- end $$;

-- ---------------------------------------------------------------------------
-- 3. 실시간(Realtime) 활성화
-- ---------------------------------------------------------------------------

do $$
declare
  t text;
begin
  foreach t in array array['transactions','user_settings','categories','budgets','goals','accounts','recurring','settlements','app_settings']
  loop
    begin
      execute format('alter publication supabase_realtime add table public.%I', t);
    exception when duplicate_object then
      null; -- 이미 추가되어 있으면 통과
    end;
  end loop;
end $$;

-- 삭제 이벤트에서 이전 행 정보를 받기 위해 필요합니다
alter table public.transactions  replica identity full;
alter table public.budgets       replica identity full;
alter table public.goals         replica identity full;
alter table public.categories    replica identity full;
alter table public.user_settings replica identity full;
alter table public.accounts      replica identity full;
alter table public.recurring     replica identity full;
alter table public.settlements   replica identity full;
alter table public.app_settings  replica identity full;

-- ---------------------------------------------------------------------------
-- 4. 초기 버전이 심어둔 샘플 데이터 제거 (한 번만 실행하면 됩니다)
-- ---------------------------------------------------------------------------

delete from public.transactions
 where id like 'tx_202609/_%' escape '/'
    or id like 'h/_0%' escape '/';

delete from public.budgets where id in
  ('b_food','b_living','b_transport','b_shopping','b_relation','b_growth','b_finance','b_other');

delete from public.goals where id in ('g1','g2','g3');

delete from public.accounts where id in ('acc1','acc2','acc3','card1');
delete from public.recurring where id in ('rec_rent','rec_insurance','rec_utility');
delete from public.transactions where id like 'ctx/_%' escape '/';
delete from public.transactions where "installmentId" = 'inst_demo';

-- ---------------------------------------------------------------------------
-- 5. 확인
-- ---------------------------------------------------------------------------
-- RLS 가 9개 테이블 모두 true 여야 정상입니다.
select tablename, rowsecurity
  from pg_tables
 where schemaname = 'public'
   and tablename in ('transactions','user_settings','categories','budgets','goals',
                     'accounts','recurring','settlements','app_settings')
 order by tablename;
